language: ruby
cache: bundler
rvm:
- 2.6.3

script:
  - bundle exec rake build
  # this next line runs HTMLProofer on your built site; find out more at https://github.com/gjtorikian/html-proofer
  # - bundle exec rake test

# comment these lines to disable auto-deploy to github pages
# this will fail if you don't set github_token in Travis!
deploy:
  provider: pages
  skip_cleanup: true
  github_token: $github_token
  local_dir: _site
  on:
    branch: master

sudo: false
